version: "3"

services:
  #  db:
  #    image: postgres
  web:
    build: .
    command: gunicorn fin_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    depends_on:
#      - db
