version: "3.7"

services:
  web:
    build: .
    command: gunicorn fin_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=putin
      - POSTGRES_PASSWORD=cyka_blyat
      - POSTGRES_DB=bradavka
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
    driver: local
