version: "3.7"

services:
  web:
    build: .
    command: gunicorn fin_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=putin
      - POSTGRES_PASSWORD=cyka_blyat
      - POSTGRES_DB=bradavka
volumes:
  postgres_data:
